# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'modulo06' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for modulo06
  target 'modulo06Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'modulo06-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
end

